### ISSUE TITLE
Request: push latest to pypi

### ISSUE THREAD

**Issue by arielf** [adiralashiva8/pytest-email#4]
Hi @adiralashiva8 

Seem like pypi.org has an older version (Jun 24) of `pytest-email` vs. latest (Jun 25).
Could you please publish latest to https://pypi.org/project/pytest-email so `pip install` finds latest?

Thank you!

**Comment by adiralashiva8** [comment]
Planning to make few ui changes will create new release. Until please use following command to install latest changes

`pip install git+https://github.com/adiralashiva8/pytest-email`

**Comment by arielf** [comment]
Thanks @adiralashiva8 

Just to clarify: I was trying to avoid the `pip install git+...` because I'm trying to create a docker image and this means requiring `git` to be installed in the container before image can be built. I'm also familiar with two stage builds in docker, but trying to simplify so being able to do direct `pip` from `pypi` would be cool. Thanks again!

**Comment by adiralashiva8** [comment]
Sorry @arielf , created new release `0.3` please let me know if any changes required

**Comment by arielf** [comment]
@adiralashiva8  Thanks for the publish.

The only thing I would change (not critical or urgent though) is avoiding the DOS style CRLF line endings in released python source code. Anyway, everything works now. Thank you!
